name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.2.9'

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install autoconf
        brew install automake
        brew install libtool
        brew install ninja

    - name: Build
      run: |
        make build enable-split-platform
    
    - name: Update Package.swift
      run: |
        rm -f ./Package.swift
        cp -f ./docs/Package.template.swift ./Package.swift

        MoltenVK_url="https://github.com/mpvkit/moltenvk-build/releases/download/${{ github.event.inputs.version }}/MoltenVK.xcframework.zip"
        MoltenVK_checksum=$(cat ./dist/release/MoltenVK.xcframework.checksum.txt)
        sed -i '' "s#\\\(MoltenVK_url)#${MoltenVK_url}#g" ./Package.swift
        sed -i '' "s#\\\(MoltenVK_checksum)#${MoltenVK_checksum}#g" ./Package.swift

    - name: Push Package.swift
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: |
          - Package.swift
        message: "chore: release version ${{ github.event.inputs.version }}"
        push: "origin HEAD:${{ github.ref_name }}"
        
    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        files: |
          ./dist/release/*.txt
          ./dist/release/*.zip
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        fail_on_unmatched_files: true
